server:
  port: 8082

funcell:
  security:
    credentialsHashAlgorithmName: md5
    credentialsHashIterations: 2
  jwt:
    header: Authorization
    tokenHead: Bearer
    secret: shop_sys_service
    expiration: 1800000
    claim_key_username: username
    claim_key_createdate: createdate
    authpath:
  redis:
    prefix: shop_sys_service_
    expiration: 600

spring:
  resources:
    add-mappings: false
  session:
    store-type: none
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  cache:
    type: redis
  redis:   #redis 配置
    host: localhost
    port: 6009
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000

  messages: #国际化
    basename: i18n/messages,i18n/ValidationMessages
  mvc: # 捕获404
    throw-exception-if-no-handler-found: true
  #  resources:
  #    add-mappings: false
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  aop:  #使用CGLIB来实现AOP的时候
    proxy-target-class: true

  #DATABASE CONFIG
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/funcell_haibao_store?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000


#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.funcell.shop.sys.service.modules.*.entity  #这里是实体类的位置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  com.funcell.shop.sys.service.modules.*.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型

wx:
  properties:
    appid: wx45f2cde7bb536e21
    appsecret: 70ab965a343a524528ff73973e2d077d
    granttype: authorization_code
    merchantid: unknow

#xxl定时任务部署
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: tomato_shop
      ip:
      port: 9999
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken: